# Generated by Django 2.2.5 on 2019-09-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rd4holemodel_rd4scoremodel_rd4slotmodel_rd4stablefordmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='evententrymodel',
            name='category',
            field=models.CharField(blank=True, choices=[('Round1Golf', 'Round1Golf'), ('Round1CTP-LD', 'Round1CTP-LD'), ('Round1Other', 'Round1Other')], max_length=10, null=True),
        ),
    ]
