# Generated by Django 2.2.5 on 2019-09-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190929_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardmodel',
            name='player',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
