# Generated by Django 2.2.5 on 2019-09-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190929_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='leaderboardmodel',
            name='total_points',
        ),
        migrations.AlterField(
            model_name='evententrymodel',
            name='category',
            field=models.CharField(blank=True, choices=[('Round1Golf', 'Round1Golf'), ('Round1CTPLD', 'Round1CTPLD'), ('Round1_Bonus', 'Round1_Bonus')], max_length=30, null=True),
        ),
    ]
