# Generated by Django 2.2.5 on 2019-10-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190929_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardmodel',
            name='best_dressed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='other_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='overall_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='rd2_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='rd2_ctpld',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='rd2_golf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='rd2_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='rd3_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='rd3_ctpld',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='rd3_golf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='rd3_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='social',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='leaderboardmodel',
            name='tipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='evententrymodel',
            name='category',
            field=models.CharField(blank=True, choices=[('Round1Golf', 'Round1Golf'), ('Round1CTPLD', 'Round1CTPLD'), ('Round1_Bonus', 'Round1_Bonus'), ('Round2Golf', 'Round2Golf'), ('Round2CTPLD', 'Round2CTPLD'), ('Round2_Bonus', 'Round2_Bonus'), ('Round3Golf', 'Round3Golf'), ('Round3CTPLD', 'Round3CTPLD'), ('Round3_Bonus', 'Round3_Bonus'), ('Social', 'Social'), ('Best_dressed', 'Best_dressed'), ('Tipping', 'Tipping')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game1',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('ROCKETS', 'Rockets'), ('NETS', 'Nets')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game10',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('MIAMI', 'Miami'), ('FLORIDA_STATE', 'Florida State')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game2',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('LIGHTNING', 'Lightning'), ('ISLANDERS', 'Islanders')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game3',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('OILERS', 'Oilers'), ('PENGUINS', 'Penguins')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game4',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('RAPTORS', 'Raptors'), ('BUCKS', 'Bucks')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game5',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('CRYSTAL_PALACE', 'Crystal Palace'), ('LEICESTER_CITY', 'Leicester City'), ('DRAW', 'Draw')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game6',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('ARSENAL', 'Arsenal'), ('WOLVERHAMPTON', 'Wolverhampton'), ('DRAW', 'Draw')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game7',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('OLE_MISS', 'Ole Miss'), ('AUBURN', 'Auburn')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game8',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('OREGON', 'Oregon'), ('USC', 'USC')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingmodel',
            name='game9',
            field=models.CharField(blank=True, choices=[('', 'Select result'), ('GEORGIA', 'Georgia'), ('FLORIDA', 'Florida')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result1',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('ROCKETS', 'Rockets'), ('NETS', 'Nets')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result10',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('MIAMI', 'Miami'), ('FLORIDA_STATE', 'Florida State')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result2',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('LIGHTNING', 'Lightning'), ('ISLANDERS', 'Islanders')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result3',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('OILERS', 'Oilers'), ('PENGUINS', 'Penguins')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result4',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('RAPTORS', 'Raptors'), ('BUCKS', 'Bucks')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result5',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('CRYSTAL_PALACE', 'Crystal Palace'), ('LEICESTER_CITY', 'Leicester City'), ('DRAW', 'Draw')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result6',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('ARSENAL', 'Arsenal'), ('WOLVERHAMPTON', 'Wolverhampton'), ('DRAW', 'Draw')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result7',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('OLE_MISS', 'Ole Miss'), ('AUBURN', 'Auburn')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result8',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('OREGON', 'Oregon'), ('USC', 'USC')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportstippingresultsmodel',
            name='result9',
            field=models.CharField(blank=True, choices=[('NOT_COMPLETE', 'No result'), ('GEORGIA', 'Georgia'), ('FLORIDA', 'Florida')], max_length=20, null=True),
        ),
    ]
