# Generated by Django 2.2.5 on 2019-10-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191004_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='highfinish',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
