# Generated by Django 2.2.5 on 2019-10-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_playermodel_highfinish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rd1EnduranceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=30, null=True)),
                ('firstnine_stbl', models.IntegerField(blank=True, null=True)),
                ('secondnine_stbl', models.IntegerField(blank=True, null=True)),
                ('endurance_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
