# Generated by Django 2.2.5 on 2019-10-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rd1endurancemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rd1endurancemodel',
            name='slot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rd1slotmodel',
            name='endurance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
